<div class="row">
    <div class="col-lg-12">
        <div id="InsideFooter">
            <div id="footerklantenservice">
                <h4>Klantenservice<br></h4>
                <a>reparatie</a><br>
                <a href="?page=login">inloggen</a><br>
                <a>retourneren</a><br>
                <a href="?page=contact">vragen</a><br>
                <a>privacy</a><br>
            </div>
            <div id="footerContact">
                <h4>Contact<br></h4>
                tel 45-45565734<br>
                winkelstraat 1<br>
                1111 AA Doetinchem<br>
                infor@pc4u.com<br><br><br><br><br>
            </div>
            <div id="footerBetaal">
                <h4>Betaalmethode<br></h4>
                <img src="images/Paypal1.1.png"><br>
                <img class="IDEAL" src="images/iDEAL.png"><br>
                <img class="Betaalmethode" src="images/Visa.png"><br>
                <img class="Betaalmethode" src="images/mastercard-180x113.png">
            </div>
            <div id="footerSocial">
                <table>
                    <tr>
                        <td>Twitter</td>
                        <td><img class="Soc" src="images/twitter.png"></td>

                    </tr>
                    <tr>
                        <td>Facebook</td>
                        <td><img class="Soc" src="images/FBtest.png"></td>

                    </tr>
                    <tr>
                        <td>Instagram</td>
                        <td><img class="Soc" src="images/instagram.png"></td>

                    </tr>
                    <tr>
                        <td>Google+</td>
                        <td><img class="Soc" src="images/google.png"></td>

                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg-12">
            <hr>
            <div id="Copyright">
                Algemene copyright © pc4u.com - alle prijzen inclusief BTW
            </div>
        </div>
    </div>
</div>