<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
    <a class="navbar-brand" href="http://jhdev.nl/pc4u"><img class="logo" src="images/pc4u.png"></a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <div class="centerheader">

    </div>
    <div class="leftheader">
        <img href="?page=shopcart" class="image" src="images/winkelwagen.png">
        <img href="?page=service" class="image" src="images/reperatie.png">
        <div class="tooltip">
            <img class="image" onclick="location.href='?page=login';" src="images/profiel.PNG">
            <table class="tooltiptext">
                <tr>
                    <td><p class="blackp">U bent nog niet ingelogd.</p></td>
                </tr><tr>
                    <td><p class="blackp"><a href="?page=login">Klik hier als u wilt inloggen.</a></p></td>
                </tr>
            </table></div>
    </div>
</div>
