<div class="list-group">
    <a href="?page=productspage&mcat=desktop" class="list-group-item"><h3>Desktop</h3></a>
    <a href="?page=productspage&scat=compleet" class="list-group-item"><p>-compleet</p></a>
    <a href="?page=productspage&scat=behuizingen" class="list-group-item"><p>-behuizingen</p></a>
    <a href="?page=productspage&scat=componenten" class="list-group-item"><p>-componenten</p></a>
    <a href="?page=productspage&scat=monitoren" class="list-group-item"><p>-monitoren</p></a>
    <a href="?page=productspage&mcat=laptop" class="list-group-item"><h3>Laptop</h3></a>
    <a href="?page=productspage&scat=notebook" class="list-group-item"><p>-notebook</p></a>
    <a href="?page=productspage&scat=chromebook" class="list-group-item"><p>-chromebook</p></a>
    <a href="?page=productspage&scat=ultrabook" class="list-group-item"><p>-ultrabook</p></a>
    <a href="?page=productspage&scat=tablet" class="list-group-item"><p>-tablet</p></a>
    <a href="?page=productspage&mcat=geluid" class="list-group-item"><h3>Geluid</h3></a>
    <a href="?page=productspage&scat=headset" class="list-group-item"><p>-headset</p></a>
    <a href="?page=productspage&scat=headphone" class="list-group-item"><p>-headphone</p></a>
    <a href="?page=productspage&scat=stereo" class="list-group-item"><p>-stereo</p></a>
    <a href="?page=productspage&mcat=accessoire" class="list-group-item"><h3>Accessoire</h3></a>
    <a href="?page=productspage&scat=muizen" class="list-group-item"><p>-muizen</p></a>
    <a href="?page=productspage&scat=toetsenborden" class="list-group-item"><p>-toetsenborden</p></a>
    <a href="?page=productspage&scat=oplader" class="list-group-item"><p>-oplader</p></a>
    <a href="?page=productspage&scat=muismatten" class="list-group-item"><p>-muismatten</p></a>
    <a href="?page=productspage&scat=usb" class="list-group-item"><p>-usb-sticks</p></a>
    <a href="?page=productspage&scat=externe" class="list-group-item"><p>-externe hdd's</p></a>
</div>