<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
    <a class="navbar-brand" href="http://jhdev.nl/pc4u"><img class="logo" src="images/pc4u.png"></a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <div class="centerheader">
        <h1>Admin paneel</h1>
    </div>
    <div class="leftheader">
        <a href="?page=../php/logout" title="Uitloggen" ><img class="image" src="images/LogOut.png"></a>
    </div>
</div>

