<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
    <a class="navbar-brand" href="http://jhdev.nl/pc4u"><img class="logo" src="images/pc4u.png"></a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <div class="centerheader">

    </div>
    <div class="leftheader">
        <a href="?page=logout"><img class="image" src="images/LogOut.png"></a>
        <a href="?page=shopcart"><img class="image" src="images/winkelwagen.png"></a>
        <a href="?page=service"><img class="image" src="images/reperatie.png"></a>
        <a href="?page=login"><img class="image" src="images/profiel.PNG"></a>
    </div>
</div>
